package com.jeff.pets.client.mixin.client;

import com.jeff.pets.PetsInitializer;
import com.jeff.pets.client.rendering.custom.aprilfools.head.HeadRenderer;
import com.jeff.pets.client.rendering.custom.first.duck.DuckRenderer;
import com.jeff.pets.client.rendering.custom.first.penguin.PenguinRenderer;
import com.jeff.pets.client.rendering.custom.first.racoon.RacoonRenderer;
import com.jeff.pets.client.rendering.vanilla.allay.ClientAllayRenderer;
import com.jeff.pets.client.rendering.vanilla.armadillo.ClientArmadilloRenderer;
import com.jeff.pets.client.rendering.vanilla.axolotl.ClientAxolotlRenderer;
import com.jeff.pets.client.rendering.vanilla.cat.ClientCatRenderer;
import com.jeff.pets.client.rendering.vanilla.sheep.ClientSheepRenderer;
import net.minecraft.client.renderer.entity.EntityRenderer;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.world.entity.EntityType;

import com.jeff.pets.client.rendering.aprilfools.angryghast.AngryGhastRenderer;
import com.jeff.pets.client.rendering.aprilfools.batato.BatatoRenderer;
import com.jeff.pets.client.rendering.aprilfools.diamondchicken.DiamondChickenRenderer;
import com.jeff.pets.client.rendering.aprilfools.lovegolem.LoveGolemRenderer;
import com.jeff.pets.client.rendering.aprilfools.megaspud.MegaSpudRenderer;
import com.jeff.pets.client.rendering.aprilfools.mooncow.MoonCowRenderer;
import com.jeff.pets.client.rendering.aprilfools.nerdcreeper.NerdCreeperRenderer;
import com.jeff.pets.client.rendering.aprilfools.pinkwither.PinkWitherRenderer;
import com.jeff.pets.client.rendering.aprilfools.plaguewhale.PlaguewhaleRenderer;
import com.jeff.pets.client.rendering.aprilfools.poisonouspotatozombie.PoisonousPotatoZombieRenderer;
import com.jeff.pets.client.rendering.aprilfools.potatohusk.PotatoHuskRenderer;
import com.jeff.pets.client.rendering.aprilfools.raytracing.RayTracingRenderer;
import com.jeff.pets.client.rendering.aprilfools.redstonebug.RedstoneBugRenderer;
import com.jeff.pets.client.rendering.aprilfools.smilingcreeper.SmilingCreeperRenderer;
import com.jeff.pets.client.rendering.aprilfools.toxifin.ToxifinRenderer;
import com.jeff.pets.client.rendering.aprilfools.traitor.TraitorRenderer;
import com.jeff.pets.client.rendering.custom.aquatic.dumbo_octopus.DumboOctopusRenderer;
import com.jeff.pets.client.rendering.custom.aquatic.koi.KoiRenderer;
import com.jeff.pets.client.rendering.custom.aquatic.stingray.StingrayRenderer;
import com.jeff.pets.client.rendering.vanilla.bat.ClientBatRenderer;
import com.jeff.pets.client.rendering.vanilla.bee.ClientBeeRenderer;
import com.jeff.pets.client.rendering.vanilla.blaze.ClientBlazeRenderer;
import com.jeff.pets.client.rendering.vanilla.bogged.ClientBoggedRenderer;
import com.jeff.pets.client.rendering.vanilla.breeze.ClientBreezeRenderer;
import com.jeff.pets.client.rendering.vanilla.camel.ClientCamelRenderer;
import com.jeff.pets.client.rendering.vanilla.cavespider.ClientCaveSpiderRenderer;
import com.jeff.pets.client.rendering.vanilla.chicken.ClientChickenRenderer;
import com.jeff.pets.client.rendering.vanilla.cod.ClientCodRenderer;
import com.jeff.pets.client.rendering.vanilla.coppergolem.ClientCopperGolemRenderer;
import com.jeff.pets.client.rendering.vanilla.cow.ClientCowRenderer;
import com.jeff.pets.client.rendering.vanilla.creaking.ClientCreakingRenderer;
import com.jeff.pets.client.rendering.vanilla.creeper.ClientCreeperRenderer;
import com.jeff.pets.client.rendering.vanilla.dolphin.ClientDolphinRenderer;
import com.jeff.pets.client.rendering.vanilla.donkey.ClientDonkeyRenderer;
import com.jeff.pets.client.rendering.vanilla.drowned.ClientDrownedRenderer;
import com.jeff.pets.client.rendering.vanilla.elderguardian.ClientElderGuardianRenderer;
import com.jeff.pets.client.rendering.vanilla.enderdragon.ClientEnderDragonRenderer;
import com.jeff.pets.client.rendering.vanilla.enderman.ClientEndermanRenderer;
import com.jeff.pets.client.rendering.vanilla.endermite.ClientEndermiteRenderer;
import com.jeff.pets.client.rendering.vanilla.evoker.ClientEvokerRenderer;
import com.jeff.pets.client.rendering.vanilla.fox.ClientFoxRenderer;
import com.jeff.pets.client.rendering.vanilla.frog.ClientFrogRenderer;
import com.jeff.pets.client.rendering.vanilla.ghast.ClientGhastRenderer;
import com.jeff.pets.client.rendering.vanilla.goat.ClientGoatRenderer;
import com.jeff.pets.client.rendering.vanilla.guardian.ClientGuardianRenderer;
import com.jeff.pets.client.rendering.vanilla.happyghast.ClientHappyGhastRenderer;
import com.jeff.pets.client.rendering.vanilla.hoglin.ClientHoglinRenderer;
import com.jeff.pets.client.rendering.vanilla.horse.ClientHorseRenderer;
import com.jeff.pets.client.rendering.vanilla.husk.ClientHuskRenderer;
import com.jeff.pets.client.rendering.vanilla.irongolem.ClientIronGolemRenderer;
import com.jeff.pets.client.rendering.vanilla.llama.ClientLlamaRenderer;
import com.jeff.pets.client.rendering.vanilla.magmacube.ClientMagmaCubeRenderer;
import com.jeff.pets.client.rendering.vanilla.mooshroom.ClientMooshroomRenderer;
import com.jeff.pets.client.rendering.vanilla.nautilus.ClientNautilusRenderer;
import com.jeff.pets.client.rendering.vanilla.panda.ClientPandaRenderer;
import com.jeff.pets.client.rendering.vanilla.parched.ClientParchedRenderer;
import com.jeff.pets.client.rendering.vanilla.parrot.ClientParrotRenderer;
import com.jeff.pets.client.rendering.vanilla.phantom.ClientPhantomRenderer;
import com.jeff.pets.client.rendering.vanilla.pig.ClientPigRenderer;
import com.jeff.pets.client.rendering.vanilla.piglin.ClientPiglinRenderer;
import com.jeff.pets.client.rendering.vanilla.pillager.ClientPillagerRenderer;
import com.jeff.pets.client.rendering.vanilla.polarbear.ClientPolarBearRenderer;
import com.jeff.pets.client.rendering.vanilla.pufferfish.ClientPufferFishRenderer;
import com.jeff.pets.client.rendering.vanilla.rabbit.ClientRabbitRenderer;
import com.jeff.pets.client.rendering.vanilla.ravager.ClientRavagerRenderer;
import com.jeff.pets.client.rendering.vanilla.salmon.ClientSalmonRenderer;
import com.jeff.pets.client.rendering.vanilla.shulker.ClientShulkerRenderer;
import com.jeff.pets.client.rendering.vanilla.silverfish.ClientSilverfishRenderer;
import com.jeff.pets.client.rendering.vanilla.skeleton.ClientSkeletonRenderer;
import com.jeff.pets.client.rendering.vanilla.slime.ClientSlimeRenderer;
import com.jeff.pets.client.rendering.vanilla.sniffer.ClientSnifferRenderer;
import com.jeff.pets.client.rendering.vanilla.snowgolem.ClientSnowGolemRenderer;
import com.jeff.pets.client.rendering.vanilla.spider.ClientSpiderRenderer;
import com.jeff.pets.client.rendering.vanilla.squid.ClientSquidRenderer;
import com.jeff.pets.client.rendering.vanilla.stray.ClientStrayRenderer;
import com.jeff.pets.client.rendering.vanilla.strider.ClientStriderRenderer;
import com.jeff.pets.client.rendering.vanilla.tadpole.ClientTadpoleRenderer;
import com.jeff.pets.client.rendering.vanilla.turtle.ClientTurtleRenderer;
import com.jeff.pets.client.rendering.vanilla.vex.ClientVexRenderer;
import com.jeff.pets.client.rendering.vanilla.villager.ClientVillagerRenderer;
import com.jeff.pets.client.rendering.vanilla.vindicator.ClientVindicatorRenderer;
import com.jeff.pets.client.rendering.vanilla.wanderingtrader.ClientWanderingTraderRenderer;
import com.jeff.pets.client.rendering.vanilla.warden.ClientWardenRenderer;
import com.jeff.pets.client.rendering.vanilla.witch.ClientWitchRenderer;
import com.jeff.pets.client.rendering.vanilla.wither.ClientWitherRenderer;
import com.jeff.pets.client.rendering.vanilla.witherskeleton.ClientWitherSkeletonRenderer;
import com.jeff.pets.client.rendering.vanilla.wolf.ClientWolfRenderer;
import com.jeff.pets.client.rendering.vanilla.zombie.ClientZombieRenderer;
import com.jeff.pets.client.rendering.vanilla.zombievillager.ClientZombieVillagerRenderer;

import java.util.HashMap;
import java.util.Map;

public class EntityRenderersDelegate {

    @SuppressWarnings({"unchecked", "rawtypes"})
    public static Map<EntityType<?>, EntityRenderer<?, ?>> appendCustomRenderers(
            Map<EntityType<?>, EntityRenderer<?, ?>> vanillaMap,
            EntityRendererProvider.Context context
    ) {

        Map<EntityType<?>, EntityRenderer<?, ?>> mutableMap = new HashMap<>(vanillaMap);

            try {
                mutableMap.put(PetsInitializer.HEAD, new HeadRenderer(context));
                mutableMap.put(PetsInitializer.DUCK, new DuckRenderer(context));
                mutableMap.put(PetsInitializer.RACOON, new RacoonRenderer(context));
                mutableMap.put(PetsInitializer.PENGUIN, new PenguinRenderer(context));
                mutableMap.put(PetsInitializer.SHEEP, new ClientSheepRenderer(context));
                mutableMap.put(PetsInitializer.CAT, new ClientCatRenderer(context));
                mutableMap.put(PetsInitializer.ALLAY, new ClientAllayRenderer(context));
                mutableMap.put(PetsInitializer.ARMADILLO, new ClientArmadilloRenderer(context));
                mutableMap.put(PetsInitializer.AXOLOTL, new ClientAxolotlRenderer(context));
                mutableMap.put(PetsInitializer.BAT, new ClientBatRenderer(context));
                mutableMap.put(PetsInitializer.CAMEL, new ClientCamelRenderer(context));
                mutableMap.put(PetsInitializer.CHICKEN, new ClientChickenRenderer(context));
                mutableMap.put(PetsInitializer.COD, new ClientCodRenderer(context));
                mutableMap.put(PetsInitializer.COPPER_GOLEM, new ClientCopperGolemRenderer(context));
                mutableMap.put(PetsInitializer.COW, new ClientCowRenderer(context));
                mutableMap.put(PetsInitializer.DONKEY, new ClientDonkeyRenderer(context));
                mutableMap.put(PetsInitializer.FROG, new ClientFrogRenderer(context));
                mutableMap.put(PetsInitializer.HORSE, new ClientHorseRenderer(context));
                mutableMap.put(PetsInitializer.MOOSHROOM, new ClientMooshroomRenderer(context));
                mutableMap.put(PetsInitializer.PARROT, new ClientParrotRenderer(context));
                mutableMap.put(PetsInitializer.PIG, new ClientPigRenderer(context));
                mutableMap.put(PetsInitializer.RABBIT, new ClientRabbitRenderer(context));
                mutableMap.put(PetsInitializer.SALMON, new ClientSalmonRenderer(context));
                mutableMap.put(PetsInitializer.SNIFFER, new ClientSnifferRenderer(context));
                mutableMap.put(PetsInitializer.SNOW_GOLEM, new ClientSnowGolemRenderer(context));
                mutableMap.put(PetsInitializer.SQUID, new ClientSquidRenderer(context));
                mutableMap.put(PetsInitializer.STRIDER, new ClientStriderRenderer(context));
                mutableMap.put(PetsInitializer.TADPOLE, new ClientTadpoleRenderer(context));
                mutableMap.put(PetsInitializer.TURTLE, new ClientTurtleRenderer(context));
                mutableMap.put(PetsInitializer.VILLAGER, new ClientVillagerRenderer(context));
                mutableMap.put(PetsInitializer.WANDERING_TRADER, new ClientWanderingTraderRenderer(context));
                mutableMap.put(PetsInitializer.BEE, new ClientBeeRenderer(context));
                mutableMap.put(PetsInitializer.CAVE_SPIDER, new ClientCaveSpiderRenderer(context));
                mutableMap.put(PetsInitializer.DOLPHIN, new ClientDolphinRenderer(context));
                mutableMap.put(PetsInitializer.ENDERMAN, new ClientEndermanRenderer(context));
                mutableMap.put(PetsInitializer.FOX, new ClientFoxRenderer(context));
                mutableMap.put(PetsInitializer.GOAT, new ClientGoatRenderer(context));
                mutableMap.put(PetsInitializer.IRON_GOLEM, new ClientIronGolemRenderer(context));
                mutableMap.put(PetsInitializer.LLAMA, new ClientLlamaRenderer(context));
                mutableMap.put(PetsInitializer.NAUTILUS, new ClientNautilusRenderer(context));
                mutableMap.put(PetsInitializer.PANDA, new ClientPandaRenderer(context));
                mutableMap.put(PetsInitializer.PIGLIN, new ClientPiglinRenderer(context));
                mutableMap.put(PetsInitializer.POLAR_BEAR, new ClientPolarBearRenderer(context));
                mutableMap.put(PetsInitializer.PUFFERFISH, new ClientPufferFishRenderer(context));
                mutableMap.put(PetsInitializer.SPIDER, new ClientSpiderRenderer(context));
                mutableMap.put(PetsInitializer.WOLF, new ClientWolfRenderer(context));
                mutableMap.put(PetsInitializer.ELDER_GUARDIAN_COOKIE, new ClientElderGuardianRenderer(context));
                mutableMap.put(PetsInitializer.HAPPY_GHAST, new ClientHappyGhastRenderer(context));
                mutableMap.put(PetsInitializer.BLAZE, new ClientBlazeRenderer(context));
                mutableMap.put(PetsInitializer.BOGGED, new ClientBoggedRenderer(context));
                mutableMap.put(PetsInitializer.BREEZE, new ClientBreezeRenderer(context));
                mutableMap.put(PetsInitializer.CREAKING, new ClientCreakingRenderer(context));
                mutableMap.put(PetsInitializer.CREEPER, new ClientCreeperRenderer(context));
                mutableMap.put(PetsInitializer.DROWNED, new ClientDrownedRenderer(context));
                mutableMap.put(PetsInitializer.ENDERMITE, new ClientEndermiteRenderer(context));
                mutableMap.put(PetsInitializer.EVOKER, new ClientEvokerRenderer(context));
                mutableMap.put(PetsInitializer.GHAST, new ClientGhastRenderer(context));
                mutableMap.put(PetsInitializer.GUARDIAN, new ClientGuardianRenderer(context));
                mutableMap.put(PetsInitializer.HOGLIN, new ClientHoglinRenderer(context));
                mutableMap.put(PetsInitializer.HUSK, new ClientHuskRenderer(context));
                mutableMap.put(PetsInitializer.MAGMA_CUBE, new ClientMagmaCubeRenderer(context));
                mutableMap.put(PetsInitializer.PARCHED, new ClientParchedRenderer(context));
                mutableMap.put(PetsInitializer.PHANTOM, new ClientPhantomRenderer(context));
                mutableMap.put(PetsInitializer.PILLAGER, new ClientPillagerRenderer(context));
                mutableMap.put(PetsInitializer.RAVAGER, new ClientRavagerRenderer(context));
                mutableMap.put(PetsInitializer.SHULKER, new ClientShulkerRenderer(context));
                mutableMap.put(PetsInitializer.SILVERFISH, new ClientSilverfishRenderer(context));
                mutableMap.put(PetsInitializer.SKELETON, new ClientSkeletonRenderer(context));
                mutableMap.put(PetsInitializer.SLIME, new ClientSlimeRenderer(context));
                mutableMap.put(PetsInitializer.STRAY, new ClientStrayRenderer(context));
                mutableMap.put(PetsInitializer.VEX, new ClientVexRenderer(context));
                mutableMap.put(PetsInitializer.VINDICATOR, new ClientVindicatorRenderer(context));
                mutableMap.put(PetsInitializer.WARDEN, new ClientWardenRenderer(context));
                mutableMap.put(PetsInitializer.WITCH, new ClientWitchRenderer(context));
                mutableMap.put(PetsInitializer.WITHER_SKELETON, new ClientWitherSkeletonRenderer(context));
                mutableMap.put(PetsInitializer.ZOMBIE, new ClientZombieRenderer(context));
                mutableMap.put(PetsInitializer.ZOMBIE_VILLAGER, new ClientZombieVillagerRenderer(context));
                mutableMap.put(PetsInitializer.ENDER_DRAGON, new ClientEnderDragonRenderer(context));
                mutableMap.put(PetsInitializer.WITHER, new ClientWitherRenderer(context));
                mutableMap.put(PetsInitializer.BATATO, new BatatoRenderer(context));
                mutableMap.put(PetsInitializer.ANGRY_GHAST, new AngryGhastRenderer(context));
                mutableMap.put(PetsInitializer.DIAMOND_CHICKEN, new DiamondChickenRenderer(context));
                mutableMap.put(PetsInitializer.LOVE_GOLEM, new LoveGolemRenderer(context));
                mutableMap.put(PetsInitializer.MEGA_SPUD, new MegaSpudRenderer(context));
                mutableMap.put(PetsInitializer.MOON_COW, new MoonCowRenderer(context));
                mutableMap.put(PetsInitializer.NERD_CREEPER, new NerdCreeperRenderer(context));
                mutableMap.put(PetsInitializer.PINK_WITHER, new PinkWitherRenderer(context));
                mutableMap.put(PetsInitializer.PLAGUEWHALE_SLAB, new PlaguewhaleRenderer(context));
                mutableMap.put(PetsInitializer.POISONOUS_POTATO_ZOMBIE, new PoisonousPotatoZombieRenderer(context));
                mutableMap.put(PetsInitializer.POTATO_HUSK, new PotatoHuskRenderer(context));
                mutableMap.put(PetsInitializer.RAY_TRACING, new RayTracingRenderer(context));
                mutableMap.put(PetsInitializer.REDSTONE_BUG, new RedstoneBugRenderer(context));
                mutableMap.put(PetsInitializer.SMILING_CREEPER, new SmilingCreeperRenderer(context));
                mutableMap.put(PetsInitializer.TOXIFIN_SLAB, new ToxifinRenderer(context));
                mutableMap.put(PetsInitializer.TRAITOR, new TraitorRenderer(context));
                mutableMap.put(PetsInitializer.DUMBO_OCTOPUS, new DumboOctopusRenderer(context));
                mutableMap.put(PetsInitializer.KOI, new KoiRenderer(context));
                mutableMap.put(PetsInitializer.STINGRAY, new StingrayRenderer(context));
            } catch (Throwable t) {
                //throw new RuntimeException(t);
            }

        return mutableMap;
    }
}