// This is a minimal setup of a Forge mod workspace.
// For complex examples (including AccessTransformers, Jar-in-Jar, and Mixin), see our examples repository.
// https://github.com/MinecraftForge/MDKExamples

plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[7.0.3,8)'
}

version = project.mod_version
group = project.maven_group

// Mojang ships Java 21 to end users in 1.20.5+, so your mod should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

// Include generated resources
sourceSets.main.resources { srcDir 'src/generated/resources' }

minecraft {
    mappings channel: 'official', version: project.minecraft_version
    accessTransformers.from(file('src/main/resources/META-INF/accesstransformer.cfg'))

    runs {

        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            systemProperty 'forge.enabledGameTestNamespaces', 'pets_mod'
        }

        register('client')

        client {
            mods {
                pets_mod {
                    source sourceSets.main
                }
            }
        }

        register('server') {
            args '--nogui'
        }

        register('gameTestServer')

        register('data') {
            workingDir = layout.projectDirectory.dir('run-data')

            args '--mod', 'pets_mod', '--all', '--output', layout.projectDirectory.dir('src/generated/resources'), '--existing', layout.projectDirectory.dir('src/main/resources')
        }
    }
}

repositories {
    minecraft.mavenizer(it) // In Kotlin, it = this
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
    maven { url "https://maven.shedaniel.me/" }

}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}")
    implementation "me.shedaniel.cloth:cloth-config-forge:${project.cloth_config_version}"
    //implementation "net.sf.jopt-simple:jopt-simple:5.0.4"
}

tasks.withType(JavaCompile).configureEach {
    // Use the UTF-8 charset for Java compilation
    // This is done by default in Java 18+, but this ensures it no matter the Java or Gradle version
    options.encoding = 'UTF-8'
}
processResources {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    from "src/main/resources"

    filesMatching('META-INF/mods.toml') {
        expand replaceProperties
    }
}

tasks.withType(Copy).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('jar') {
    archiveBaseName = "pets-mod"
    archiveVersion = project.mod_version
    archiveClassifier = project.minecraft_version + "-forge"
}
configurations.all {
    resolutionStrategy {
        force 'net.sf.jopt-simple:jopt-simple:5.0.4'
    }
}