# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.16.1
loader_version=0.18.4
loom_version=1.10-SNAPSHOT
# Mod Properties
mod_version=0.7.9
maven_group=com.jeff.pets
archives_base_name=pets-mod
# Dependencies
fabric_api_version=0.18.0+build.387-1.16.1
modmenu_version=3gwnUSKz
yacl_version=3gwnUSKz
cloth_config_version=4.6.0
jankson_version=1.2.0
toml4j_version=0.7.2









