package com.jeff.pets.enums;

import dev.isxander.yacl3.api.NameableEnum;
import net.minecraft.network.chat.Component;

public enum PetList implements NameableEnum {
    allay,
    armadillo,
    axolotl,
    bat,
    bee,
    blaze,
    breeze,
    camel,
    cat,
    cave_spider,
    chicken,
    cod,
    copper_golem,
    cow,
    creaking,
    creeper,
    dolphin,
    donkey,
    drowned,
    duck,
    elder_guardian,
    ender_dragon,
    enderman,
    endermite,
    evoker,
    fox,
    frog,
    ghast,
    goat,
    guardian,
    hoglin,
    horse,
    husk,
    iron_golem,
    llama,
    magma_cube,
    mooshroom,
    nautilus,
    panda,
    parrot,
    penguin,
    phantom,
    pig,
    piglin,
    pillager,
    polar_bear,
    pufferfish,
    rabbit,
    racoon,
    ravager,
    salmon,
    sheep,
    shulker,
    silverfish,
    skeleton,
    slime,
    sniffer,
    snow_golem,
    spider,
    squid,
    strider,
    tadpole,
    turtle,
    vex,
    villager,
    vindicator,
    wandering_trader,
    warden,
    witch,
    wither,
    wolf,
    zombie,
    zombie_villager;


    @Override
    public Component getDisplayName() {
        return Component.literal(String.valueOf(this));
    }
}
