package com.jeff.pets.client.enums;


public enum PetList implements NameableEnum {
    bat,
    bee,
    blaze,
    cat,
    cave_spider,
    chicken,
    cod,
    cow,
    creeper,
    dolphin,
    donkey,
    drowned,
    duck,
    dumbo_octopus,
    elder_guardian,
    ender_dragon,
    enderman,
    endermite,
    evoker,
    fox,
    ghast,
    guardian,
    happy_ghast,
    head,
    hoglin,
    horse,
    husk,
    iron_golem,
    koi,
    llama,
    magma_cube,
    mooshroom,
    panda,
    parrot,
    penguin,
    phantom,
    pig,
    piglin,
    pillager,
    polar_bear,
    pufferfish,
    rabbit,
    racoon,
    ravager,
    salmon,
    sheep,
    shulker,
    silverfish,
    skeleton,
    slime,
    snow_golem,
    spider,
    squid,
    stingray,
    strider,
    stray,
    wither_skeleton,
    turtle,
    vex,
    villager,
    vindicator,
    wandering_trader,
    witch,
    wither,
    wolf,
    zombie,
    zombie_villager;

    @Override
    public net.minecraft.util.text.ITextComponent getDisplayName() {
        return new net.minecraft.util.text.StringTextComponent(String.valueOf(this).replace("_", " "));
    }
}
