package com.jeff.pets.client.enums;


public enum PetList implements NameableEnum {
    bat,
    blaze,
    cat,
    cave_spider,
    chicken,
    cow,
    creeper,
    donkey,
    duck,
    dumbo_octopus,
    elder_guardian,
    ender_dragon,
    enderman,
    endermite,
    evoker,
    ghast,
    guardian,
    happy_ghast,
    head,
    horse,
    husk,
    iron_golem,
    koi,
    llama,
    magma_cube,
    mooshroom,
    parrot,
    penguin,
    pig,
    polar_bear,
    rabbit,
    racoon,
    sheep,
    shulker,
    silverfish,
    skeleton,
    slime,
    snow_golem,
    spider,
    squid,
    stingray,
    stray,
    wither_skeleton,
    vex,
    villager,
    vindicator,
    witch,
    wither,
    wolf,
    zombie,
    zombie_villager,
    zombie_pigman;

    @Override
    public net.minecraft.util.text.ITextComponent getDisplayName() {
        return new net.minecraft.util.text.TextComponentString(String.valueOf(this).replace("_", " "));
    }
}
